-- Add more detailed fields to properties table
ALTER TABLE public.properties
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS apartment_type TEXT,
ADD COLUMN IF NOT EXISTS floor TEXT,
ADD COLUMN IF NOT EXISTS elevator BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS furnished BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS balcony BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS parking BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS pets_allowed BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS move_in_date TEXT,
ADD COLUMN IF NOT EXISTS deposit TEXT,
ADD COLUMN IF NOT EXISTS prepaid_rent TEXT,
ADD COLUMN IF NOT EXISTS utilities_included BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS heating_type TEXT,
ADD COLUMN IF NOT EXISTS energy_rating TEXT,
ADD COLUMN IF NOT EXISTS year_built TEXT,
ADD COLUMN IF NOT EXISTS features TEXT[];